/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.pepsico.controller;

import com.pepsico.model.CreateMenu;
import com.pepsico.model.CreateMenuItem;
import com.pepsico.model.Menu;
import com.pepsico.model.MenuItem;
import com.pepsico.model.ModelApiResponse;
// import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-12-08T12:58:27.435673+05:30[Asia/Calcutta]")
@Validated
// @Api(value = "v1", description = "the v1 API")
public interface V1Api {

    default V1ApiDelegate getDelegate() {
        return new V1ApiDelegate() {};
    }

    /**
     * POST /v1/menus : Adds a new menu to the given customer
     * Adds a new menu to the given customer
     *
     * @param customerId specific customerId that the menu belongs to (required)
     * @param createMenu  (optional)
     * @return successful operation (status code 200)
     *         or Invalid customerId or menu value (status code 400)
     *         or Access token is missing or invalid (status code 401)
     *         or No customer exists for the given customerId (status code 404)
     */
    
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/menus",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<String> createMenu(
        String customerId,
        CreateMenu createMenu) {
        return getDelegate().createMenu(customerId, createMenu);
    }


    /**
     * POST /v1/menuItems : Adds a new menuItem to the given Menu
     * Adds a new menuItem to the given Menu
     *
     * @param menuId specific menu id that the menuitem belongs to (required)
     * @param createMenuItem MenuItem object that needs to be added to the menu (optional)
     * @return successful operation (status code 200)
     *         or Invalid menuId or menuItem value (status code 400)
     *         or Access token is missing or invalid (status code 401)
     *         or No menu exists for the given menuId (status code 404)
     */
    // @ApiOperation(value = "Adds a new menuItem to the given Menu", nickname = "createMenuItem", notes = "Adds a new menuItem to the given Menu", response = String.class, authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menuItems", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = String.class),
    //     @ApiResponse(code = 400, message = "Invalid menuId or menuItem value"),
    //     @ApiResponse(code = 401, message = "Access token is missing or invalid"),
    //     @ApiResponse(code = 404, message = "No menu exists for the given menuId") })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/menuItems",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<String> createMenuItem(
        String menuId,
        CreateMenuItem createMenuItem) {
        return getDelegate().createMenuItem(menuId, createMenuItem);
    }


    /**
     * DELETE /v1/menus/{menuId} : Delete a menu by ID
     * Deletes the specified menu using its ID.
     *
     * @param menuId ID of menu to be deleted (required)
     * @return No Content. The item was successfully deleted. (status code 204)
     *         or Not Found. The item with the specified ID was not found. (status code 404)
     *         or Internal Server Error. An error occurred during the operation. (status code 500)
     */
    // @ApiOperation(value = "Delete a menu by ID", nickname = "deleteMenuById", notes = "Deletes the specified menu using its ID.", authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menus", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 204, message = "No Content. The item was successfully deleted."),
    //     @ApiResponse(code = 404, message = "Not Found. The item with the specified ID was not found."),
    //     @ApiResponse(code = 500, message = "Internal Server Error. An error occurred during the operation.") })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/v1/menus/{menuId}"
    )
    default ResponseEntity<Void> deleteMenuById(
         String menuId) {
        return getDelegate().deleteMenuById(menuId);
    }


    /**
     * DELETE /v1/menuItems/{menuItemId} : Delete a minuItem by ID
     * Deletes the specified menuItem using its ID.
     *
     * @param menuItemId ID of menuItem to be deleted (required)
     * @return No Content. The item was successfully deleted. (status code 204)
     *         or Not Found. The item with the specified ID was not found. (status code 404)
     *         or Internal Server Error. An error occurred during the operation. (status code 500)
     */
    // @ApiOperation(value = "Delete a minuItem by ID", nickname = "deleteMenuItemById", notes = "Deletes the specified menuItem using its ID.", authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menuItems", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 204, message = "No Content. The item was successfully deleted."),
    //     @ApiResponse(code = 404, message = "Not Found. The item with the specified ID was not found."),
    //     @ApiResponse(code = 500, message = "Internal Server Error. An error occurred during the operation.") })
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/v1/menuItems/{menuItemId}"
    )
    default ResponseEntity<Void> deleteMenuItemById(String menuItemId) {
        return getDelegate().deleteMenuItemById(menuItemId);
    }


    /**
     * GET /v1/menus/{menuId} : Find menu by ID
     * Returns a single menu
     *
     * @param menuId ID of menu to return (required)
     * @return successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Menu not found (status code 404)
     */
    // @ApiOperation(value = "Find menu by ID", nickname = "getMenuById", notes = "Returns a single menu", response = Menu.class, authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menus", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = Menu.class),
    //     @ApiResponse(code = 400, message = "Invalid ID supplied"),
    //     @ApiResponse(code = 404, message = "Menu not found") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/menus/{menuId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Menu> getMenuById(String menuId) {
        return getDelegate().getMenuById(menuId);
    }


    /**
     * GET /v1/menuItems/{menuItemId} : Find menu item by ID
     * Returns a single menu item
     *
     * @param menuItemId ID of menuItem to return (required)
     * @return successful operation (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Menu not found (status code 404)
     */
    // @ApiOperation(value = "Find menu item by ID", nickname = "getMenuItemById", notes = "Returns a single menu item", response = MenuItem.class, authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menuItems", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = MenuItem.class),
    //     @ApiResponse(code = 400, message = "Invalid ID supplied"),
    //     @ApiResponse(code = 404, message = "Menu not found") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/menuItems/{menuItemId}",
        produces = { "application/json" }
    )
    default ResponseEntity<MenuItem> getMenuItemById( String menuItemId) {
        return getDelegate().getMenuItemById(menuItemId);
    }


    /**
     * GET /v1/menuItems : Get menuItems for a given menu
     * Get menu items for a given menu
     *
     * @param menuId specific menu id that the menuitems belongs to (required)
     * @return successful operation (status code 200)
     *         or Invalid menuId value (status code 400)
     *         or Access token is missing or invalid (status code 401)
     *         or No menuitems found for the given menuId (status code 404)
     */
    // @ApiOperation(value = "Get menuItems for a given menu", nickname = "getMenuItems", notes = "Get menu items for a given menu", response = MenuItem.class, responseContainer = "List", authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menuItems", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = MenuItem.class, responseContainer = "List"),
    //     @ApiResponse(code = 400, message = "Invalid menuId value"),
    //     @ApiResponse(code = 401, message = "Access token is missing or invalid"),
    //     @ApiResponse(code = 404, message = "No menuitems found for the given menuId") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/menuItems",
        produces = { "application/json" }
    )
    default ResponseEntity<List<MenuItem>> getMenuItems(String menuId) {
        return getDelegate().getMenuItems(menuId);
    }


    /**
     * GET /v1/menus : Get menus for a given customer
     * Get menus for a given customer
     *
     * @param customerId specific customer id that the menu belongs to (required)
     * @return successful operation (status code 200)
     *         or Invalid customerId value (status code 400)
     *         or Access token is missing or invalid (status code 401)
     *         or No menu found for the given customerId (status code 404)
     */
    // @ApiOperation(value = "Get menus for a given customer", nickname = "getMenus", notes = "Get menus for a given customer", response = Menu.class, responseContainer = "List", authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menus", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = Menu.class, responseContainer = "List"),
    //     @ApiResponse(code = 400, message = "Invalid customerId value"),
    //     @ApiResponse(code = 401, message = "Access token is missing or invalid"),
    //     @ApiResponse(code = 404, message = "No menu found for the given customerId") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/menus",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Menu>> getMenus(String customerId) {
        return getDelegate().getMenus(customerId);
    }


    /**
     * POST /v1/menuItems/{menuItemId}/uploadImage : uploads an image for the Menu Item
     *
     * @param menuItemId ID of menuItem to update (required)
     * @param body  (optional)
     * @return successful operation (status code 200)
     */
    // @ApiOperation(value = "uploads an image for the Menu Item", nickname = "uploadFile", notes = "", response = ModelApiResponse.class, authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menuItems", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = ModelApiResponse.class) })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/menuItems/{menuItemId}/uploadImage",
        produces = { "application/json" },
        consumes = { "application/octet-stream" }
    )
    default ResponseEntity<ModelApiResponse> uploadFile(Long menuItemId, org.springframework.core.io.Resource body) {
        // return getDelegate().uploadFile(menuItemId, body);
        return null;
    }


    /**
     * POST /v1/menus/{menuId}/uploadImage : uploads an image for the overall Menu
     *
     * @param menuId ID of menu to update (required)
     * @param body  (optional)
     * @return successful operation (status code 200)
     */
    // @ApiOperation(value = "uploads an image for the overall Menu", nickname = "uploadMenuFile", notes = "", response = ModelApiResponse.class, authorizations = {
        
    //     @Authorization(value = "bearerAuth")
    //      }, tags={ "menus", })
    // @ApiResponses(value = { 
    //     @ApiResponse(code = 200, message = "successful operation", response = ModelApiResponse.class) })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/menus/{menuId}/uploadImage",
        produces = { "application/json" },
        consumes = { "application/octet-stream" }
    )
    default ResponseEntity<ModelApiResponse> uploadMenuFile( String menuId,
     org.springframework.core.io.Resource body) {
        // return getDelegate().uploadMenuFile(menuId, body);
        return null;
    }

}
